#!/bin/bash

#root permission is required
if [ `whoami` != "root" ]
then
    echo "Root permissions needed."
    exit;
fi

MOMYDIR="/usr/share/momy"

#create folders
mkdir $MOMYDIR

#Be sure grass has execution permission
chmod +x grass

#move files to momy directory
cp grass $MOMYDIR

#set the process into the start up
ln $MOMYDIR/grass /etc/init.d/grass
update-rc.d grass defaults
