#!/bin/bash
MOMYDIR="/usr/share/momy"

#root permission is required
if [ `whoami` != "root" ]
then
    echo "Root permissions needed."
    exit;
fi

#create folders
mkdir $MOMYDIR

#move files to momy directory
cp grass $MOMYDIR

#set the process into the start up
ln $MOMYDIR/grass /etc/init.d/grass
update-rc.d grass defaults
