#!/bin/bash

#root permission is required
if [ `whoami` != "root" ]
then
    echo "Root permissions needed."
    exit;
fi

#TODO Make sure the conf file has been created from conf.default

MOMYDIR="/usr/share/momy"

#create folders
mkdir $MOMYDIR

#Be sure grass has execution permission
chmod +x grass

#move files to momy directory
cp grass $MOMYDIR

#Set up the upstart script
sudo cp momy.conf /etc/init/

#install tools
apt-get -y install xprintidle

#Set up scripts to start/stop momy when suspending
sudo cp start_momy /etc/pm/power.d/
sudo cp stop_momy /etc/pm/sleep.d/
sudo chmod +x /etc/pm/power.d/momy
sudo chmod +x /etc/pm/sleep.d/momy
